name: Web App Test Template

on:
  workflow_call:
    inputs:
      python_version:
        required: true
        type: string
        default: "3.11"
        description: "Specifies the python version."
      webapp_directory:
        required: true
        type: string
        description: "Specifies the directory of the Azure Web App."

jobs:
  test:
    name: Web App Test
    runs-on: [ubuntu-latest]
    continue-on-error: false

    steps:
      # Check Out Repository
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      # Setup Python
      - name: Setup Python
        id: python_setup
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
        with:
          python-version: ${{ inputs.python_version }}
          cache: "pip"
          cache-dependency-path: |
            ${{ inputs.webapp_directory }}/requirements.txt
            requirements.txt

      # Run Python Tests
      - name: Run Python Tests
        id: python_test
        run: |
          pip install -r "${WEBAPP_DIRECTORY}/requirements.txt" -q
          pip install -r requirements.txt -q
          pytest
        env:
          WEBAPP_DIRECTORY: ${{ inputs.webapp_directory }}
