name: Web App Deploy Template

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        default: "dev"
        description: "Specifies the environment of the deployment."
      python_version:
        required: true
        type: string
        default: "3.11"
        description: "Specifies the python version."
      webapp_directory:
        required: true
        type: string
        description: "Specifies the directory of the Azure Web App."
      webapp_name:
        required: true
        type: string
        description: "Specifies the name of the Azure Web App."
      tenant_id:
        required: true
        type: string
        description: "Specifies the tenant id of the deployment."
      subscription_id:
        required: true
        type: string
        description: "Specifies the subscription id of the deployment."
    secrets:
      CLIENT_ID:
        required: true
        description: "Specifies the client id."

permissions:
  id-token: write
  contents: read

jobs:
  deployment:
    name: Web App Deploy
    runs-on: [self-hosted]
    continue-on-error: false
    environment: ${{ inputs.environment }}
    concurrency:
      group: webapp-${{ inputs.webapp_name }}-${{ inputs.environment }}
      cancel-in-progress: false

    steps:
      # Check Out Repository
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      # Setup Python
      - name: Setup Python
        id: python_setup
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
        with:
          python-version: ${{ inputs.python_version }}
          cache: "pip"
          cache-dependency-path: |
            ${{ inputs.webapp_directory }}/requirements.txt

      # Install Web App Dependencies
      - name: Resolve Web App Dependencies
        id: webapp_dependencies
        shell: bash
        run: |
          pushd "${WEBAPP_DIRECTORY}"
          python -m pip install --upgrade pip
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"
          popd
        env:
          WEBAPP_DIRECTORY: ${{ inputs.webapp_directory }}

      # Azure login
      - name: Azure login
        id: azure_login
        uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5 # v2.3.0
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ inputs.tenant_id }}
          subscription-id: ${{ inputs.subscription_id }}

      # # Deploy Web App
      # - name: Deploy Web App
      #   id: webapp_deploy
      #   uses: Azure/webapps-deploy@657f0700ea5214d56a0400d8ac5e8023c963d25d  # v3.0.6
      #   with:
      #     app-name: ${{ inputs.webapp_name }}
      #     package: ${{ inputs.webapp_directory }}
      #     startup-command: "gunicorn --bind 0.0.0.0 --worker-class uvicorn.workers.UvicornWorker --timeout 600 app.main:app"
      #     # restart: true
