name: Web App Deployment
on:
  push:
    branches:
      - main
    paths:
      - "**.py"
      - "code/copilot/**"
      - "config/**"
      - "tests/**"
      - "requirements.txt"

  pull_request:
    branches:
      - main
    paths:
      - "**.py"
      - "code/copilot/**"
      - "config/**"
      - "tests/**"
      - "requirements.txt"

jobs:
  webapp_test:
    uses: ./.github/workflows/_webappTestTemplate.yml
    name: "Web App Test"
    with:
      python_version: "3.13"
      webapp_directory: "./code/copilot"

  webapp_dev:
    uses: ./.github/workflows/_webappDeployTemplate.yml
    name: "Web App - Dev"
    needs: [webapp_test]
    with:
      environment: "dev"
      python_version: "3.13"
      webapp_directory: "./code/copilot"
      webapp_name: "bfr-dev-app001"
      tenant_id: "37963dd4-f4e6-40f8-a7d6-24b97919e452"
      subscription_id: "1fdab118-1638-419a-8b12-06c9543714a0"
    secrets:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
